import { MBTIType, ArtStyle } from './types';

export const MBTI_DATA: MBTIType[] = [
  // Analysts (Purple)
  {
    code: 'INTJ',
    name: 'Architect',
    group: 'Analysts',
    description: 'Imaginative and strategic thinkers, with a plan for everything.',
    keywords: ['Strategic', 'Intellectual', 'Independent', 'Visionary'],
    color: 'text-purple-600',
    bgGradient: 'from-purple-500 to-indigo-600',
  },
  {
    code: 'INTP',
    name: 'Logician',
    group: 'Analysts',
    description: 'Innovative inventors with an unquenchable thirst for knowledge.',
    keywords: ['Curious', 'Analytical', 'Abstract', 'Inventive'],
    color: 'text-purple-600',
    bgGradient: 'from-purple-500 to-indigo-600',
  },
  {
    code: 'ENTJ',
    name: 'Commander',
    group: 'Analysts',
    description: 'Bold, imaginative and strong-willed leaders, always finding a way.',
    keywords: ['Bold', 'Strong-willed', 'Leader', 'Efficient'],
    color: 'text-purple-600',
    bgGradient: 'from-purple-500 to-indigo-600',
  },
  {
    code: 'ENTP',
    name: 'Debater',
    group: 'Analysts',
    description: 'Smart and curious thinkers who cannot resist an intellectual challenge.',
    keywords: ['Smart', 'Curious', 'Spontaneous', 'Entrepreneurial'],
    color: 'text-purple-600',
    bgGradient: 'from-purple-500 to-indigo-600',
  },

  // Diplomats (Green)
  {
    code: 'INFJ',
    name: 'Advocate',
    group: 'Diplomats',
    description: 'Quiet and mystical, yet very inspiring and tireless idealists.',
    keywords: ['Mystical', 'Idealist', 'Creative', 'Insightful'],
    color: 'text-emerald-600',
    bgGradient: 'from-emerald-500 to-teal-600',
  },
  {
    code: 'INFP',
    name: 'Mediator',
    group: 'Diplomats',
    description: 'Poetic, kind and altruistic people, always eager to help a good cause.',
    keywords: ['Poetic', 'Kind', 'Altruistic', 'Dreamer'],
    color: 'text-emerald-600',
    bgGradient: 'from-emerald-500 to-teal-600',
  },
  {
    code: 'ENFJ',
    name: 'Protagonist',
    group: 'Diplomats',
    description: 'Charismatic and inspiring leaders, able to mesmerize their listeners.',
    keywords: ['Charismatic', 'Inspiring', 'Leader', 'Empathetic'],
    color: 'text-emerald-600',
    bgGradient: 'from-emerald-500 to-teal-600',
  },
  {
    code: 'ENFP',
    name: 'Campaigner',
    group: 'Diplomats',
    description: 'Enthusiastic, creative and sociable free spirits, who can always find a reason to smile.',
    keywords: ['Enthusiastic', 'Creative', 'Sociable', 'Energetic'],
    color: 'text-emerald-600',
    bgGradient: 'from-emerald-500 to-teal-600',
  },

  // Sentinels (Blue)
  {
    code: 'ISTJ',
    name: 'Logistician',
    group: 'Sentinels',
    description: 'Practical and fact-minded individuals, whose reliability cannot be doubted.',
    keywords: ['Practical', 'Fact-minded', 'Reliable', 'Responsible'],
    color: 'text-sky-600',
    bgGradient: 'from-sky-500 to-blue-600',
  },
  {
    code: 'ISFJ',
    name: 'Defender',
    group: 'Sentinels',
    description: 'Very dedicated and warm protectors, always ready to defend their loved ones.',
    keywords: ['Dedicated', 'Warm', 'Protective', 'Loyal'],
    color: 'text-sky-600',
    bgGradient: 'from-sky-500 to-blue-600',
  },
  {
    code: 'ESTJ',
    name: 'Executive',
    group: 'Sentinels',
    description: 'Excellent administrators, unsurpassed at managing things or people.',
    keywords: ['Administrator', 'Efficient', 'Organized', 'Direct'],
    color: 'text-sky-600',
    bgGradient: 'from-sky-500 to-blue-600',
  },
  {
    code: 'ESFJ',
    name: 'Consul',
    group: 'Sentinels',
    description: 'Extraordinarily caring, social and popular people, always eager to help.',
    keywords: ['Caring', 'Social', 'Popular', 'Helpful'],
    color: 'text-sky-600',
    bgGradient: 'from-sky-500 to-blue-600',
  },

  // Explorers (Yellow/Orange)
  {
    code: 'ISTP',
    name: 'Virtuoso',
    group: 'Explorers',
    description: 'Bold and practical experimenters, masters of all kinds of tools.',
    keywords: ['Bold', 'Practical', 'Experimenter', 'Skilled'],
    color: 'text-amber-600',
    bgGradient: 'from-amber-400 to-orange-500',
  },
  {
    code: 'ISFP',
    name: 'Adventurer',
    group: 'Explorers',
    description: 'Flexible and charming artists, always ready to explore and experience something new.',
    keywords: ['Flexible', 'Charming', 'Artist', 'Adventurous'],
    color: 'text-amber-600',
    bgGradient: 'from-amber-400 to-orange-500',
  },
  {
    code: 'ESTP',
    name: 'Entrepreneur',
    group: 'Explorers',
    description: 'Smart, energetic and very perceptive people, who truly enjoy living on the edge.',
    keywords: ['Smart', 'Energetic', 'Perceptive', 'Risk-taker'],
    color: 'text-amber-600',
    bgGradient: 'from-amber-400 to-orange-500',
  },
  {
    code: 'ESFP',
    name: 'Entertainer',
    group: 'Explorers',
    description: 'Spontaneous, energetic and enthusiastic people – life is never boring around them.',
    keywords: ['Spontaneous', 'Energetic', 'Enthusiastic', 'Fun'],
    color: 'text-amber-600',
    bgGradient: 'from-amber-400 to-orange-500',
  },
];

export const ART_STYLES: ArtStyle[] = [
  { id: '3d-render', name: '3D Character', promptModifier: '3D rendered character, Disney Pixar style, soft lighting, 8k render, octane render' },
  { id: 'cyberpunk', name: 'Cyberpunk', promptModifier: 'Cyberpunk style, neon lights, futuristic clothing, high tech, urban night background, cinematic' },
  { id: 'fantasy', name: 'High Fantasy', promptModifier: 'High fantasy digital painting, D&D character portrait, intricate armor/robes, magical atmosphere, detailed background' },
  { id: 'watercolor', name: 'Watercolor', promptModifier: 'Soft watercolor painting, artistic, dreamy, pastel colors, ink outlines' },
  { id: 'anime', name: 'Anime', promptModifier: 'High quality anime style, Studio Ghibli inspired, vibrant colors, detailed scenery' },
  { id: 'realistic', name: 'Photorealistic', promptModifier: 'Photorealistic portrait, cinematic lighting, shallow depth of field, 85mm lens, highly detailed texture' },
];
